version: "0.1"
services:
  frontend:
    build: .
    ports:
      - "0.0.0.0:3000:80"
  frontend-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "0.0.0.0:5173:5173"
    volumes:
      - .:/app